# Use root/example as user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: on-failure
    hostname: 127.0.0.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
      POSTGRES_INITDB_ARGS: --encoding=UTF8
    ports:
      - 5432:5432
    volumes:
      - /home/KraytsMan/docker_volumes/postgres/:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin-postgres:
    image: fenglc/pgadmin4
    container_name: pgadmin4-postgres
    restart: on-failure
    hostname: 127.0.0.1
    links:
      - postgres:postgres
    ports:
      - 5050:5050
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge
